/* 
Action Types
*/
// ELEVE ACTIONS
export const GET_ALL_ELEVES = 'GET_ALL_ELEVES';
export const GET_ONE_ELEVE = 'GET_ONE_ELEVE';
export const GET_ELEVES_BY_CLASSE = 'GET_ELEVES_BY_CLASSE';
export const ADD_ELEVE = 'ADD_ELEVE';
export const UPDATE_ELEVE = 'UPDATE_ELEVE';
export const DELETE_ELEVE = 'DELETE_ELEVE';

// CLASSE ACTIONS
export const GET_ALL_CLASSES = 'GET_ALL_CLASSES';
export const GET_ONE_CLASSE = 'GET_ONE_CLASSE';
export const ADD_CLASSE = 'ADD_CLASSE';
export const UPDATE_CLASSE = 'UPDATE_CLASSE';
export const DELETE_CLASSE = 'DELETE_CLASSE';

// DOMAINE ACTIONS
export const GET_ALL_DOMAINE = 'GET_ALL_DOMAINE';
export const GET_ONE_DOMAINE = 'GET_ONE_DOMAINE';
export const ADD_DOMAINE = 'ADD_DOMAINE';
export const UPDATE_DOMAINE = 'UPDATE_DOMAINE';
export const DELETE_DOMAINE = 'DELETE_DOMAINE';

// COMPETENCE ACTIONS
export const GET_ALL_COMPETENCES = 'GET_ALL_COMPETENCES';
export const GET_ALL_COMPETENCES_BY_DOMAINE = 'GET_ALL_COMPETENCES_BY_DOMAINE';
export const GET_ONE_COMPETENCE = 'GET_ONE_COMPETENCE';
export const ADD_COMPETENCE = 'ADD_COMPETENCE';
export const UPDATE_COMPETENCE = 'UPDATE_COMPETENCE';
export const DELETE_COMPETENCE = 'DELETE_COMPETENCE';
