/* 
Action Types
*/
// ELEVE ACTIONS
export const GET_ALL_ELEVES = 'GET_ALL_ELEVES';
export const GET_ONE_ELEVE = 'GET_ONE_ELEVE';
export const GET_ELEVES_BY_CLASSE = 'GET_ELEVES_BY_CLASSE';
export const ADD_ELEVE = 'ADD_ELEVE';
export const UPDATE_ELEVE = 'UPDATE_ELEVE';
export const DELETE_ELEVE = 'DELETE_ELEVE';
export const LOADING_ELEVE = 'LOADING_ELEVE';
export const ERROR_HANDLER_ELEVE = 'ERROR_HANDLER_ELEVE';

// CLASSE ACTIONS
export const GET_ALL_CLASSES = 'GET_ALL_CLASSES';
export const GET_ONE_CLASSE = 'GET_ONE_CLASSE';
export const ADD_CLASSE = 'ADD_CLASSE';
export const UPDATE_CLASSE = 'UPDATE_CLASSE';
export const DELETE_CLASSE = 'DELETE_CLASSE';
export const LOADING_CLASSE = 'LOADING_CLASSE';
export const ERROR_HANDLER_CLASSE = 'ERROR_HANDLER_CLASSE';

// DOMAINE ACTIONS
export const GET_ALL_DOMAINE = 'GET_ALL_DOMAINE';
export const GET_ALL_DOMAINE_BY_CYCLE = 'GET_ALL_DOMAINE_BY_CYCLE';
export const GET_ONE_DOMAINE = 'GET_ONE_DOMAINE';
export const ADD_DOMAINE = 'ADD_DOMAINE';
export const UPDATE_DOMAINE = 'UPDATE_DOMAINE';
export const DELETE_DOMAINE = 'DELETE_DOMAINE';
export const LOADING_DOMAINE = 'LOADING_DOMAINE';
export const ERROR_HANDLER_DOMAINE = 'ERROR_HANDLER_DOMAINE';

// COMPETENCE ACTIONS
export const GET_ALL_COMPETENCES = 'GET_ALL_COMPETENCES';
export const GET_ALL_COMPETENCES_BY_DOMAINE = 'GET_ALL_COMPETENCES_BY_DOMAINE';
export const GET_ONE_COMPETENCE = 'GET_ONE_COMPETENCE';
export const ADD_COMPETENCE = 'ADD_COMPETENCE';
export const UPDATE_COMPETENCE = 'UPDATE_COMPETENCE';
export const DELETE_COMPETENCE = 'DELETE_COMPETENCE';
export const LOADING_COMPETENCE = 'LOADING_COMPETENCE';
export const ERROR_HANDLER_COMPETENCE = 'ERROR_HANDLER_COMPETENCE';

// EVALUATION ACTIONS
export const GET_ALL_EVALUATIONS = 'GET_ALL_EVALUATIONS';
export const ADD_EVALUATION = 'ADD_EVALUATION';
export const UPDATE_EVALUATION = 'UPDATE_EVALUATION';
export const DELETE_EVALUATION = 'DELETE_EVALUATION';
export const LOADING_EVALUATION = 'LOADING_EVALUATION';
export const ERROR_HANDLER_EVALUATION = 'ERROR_HANDLER_EVALUATION';

// ENUMS ACTIONS
export const GET_ENUM_TRIMESTRES = 'GET_ENUM_TRIMESTRES';
export const GET_ENUM_CYCLES = 'GET_ENUM_CYCLES';
export const GET_ENUM_RESULTATS = 'GET_ENUM_RESULTATS';
export const ERROR_HANDLER_ENUMS = 'ERROR_HANDLER_ENUMS';